name: niri-atomic
description: Custom Fedora Atomic with Niri, Docker, and Howdy (Bluefin-DX Base)
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 43
platforms:
  - linux/amd64

modules:
  - type: dnf
    repos:
      cleanup: true
      copr:
        - yalter/niri-git
        - ronnypfannschmidt/howdy-beta
      files:
        - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      packages:
        # System & Wayland Glue
        - dbus-tools
        - dbus-daemon
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-wlr
        - wl-clipboard
        - qt5-qtwayland
        - qt6-qtwayland
        
        # Niri Desktop Environment
        - niri
        - waybar
        - fuzzel
        - mako
        - swaylock
        - swayidle
        - foot
        - below
        
        # Audio / Video (Multimedia support)
        - alsa-firmware
        - wireplumber
        - pipewire
        - pulseaudio-utils
        - pipewire-libs-extra
        - libfdk-aac
        - ffmpeg
        - ffmpeg-libs
        - ffmpegthumbnailer
        - gstreamer1-plugins-bad
        - gstreamer1-plugins-ugly
        - v4l-utils

        # Auth & Security
        - polkit
        - mate-polkit              
        - gnome-keyring
        - howdy                    
        - howdy-gtk
        - howdy-authselect

  - type: systemd
    system:
      enabled:
        - docker.service

  - type: script
    scripts:
      - install-selinux-policies.sh 

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
        install:
          - com.bitwarden.desktop          
          - com.discordapp.Discord         
          - com.google.Chrome              
          - com.spotify.Client             
          - io.missioncenter.MissionCenter 
          - org.gnome.Loupe                
          - org.gnome.FileRoller           

  - type: chezmoi
    repository: "https://github.com/boblangley/dotfiles"
    all-users: false 
    file-conflict-policy: replace 

  # Bluefin-DX already has Brew, but we keep this to ensure your limits are set
  - type: brew
    nofile-limits: true

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraMono
        - Hack
        - SourceCodePro
      google-fonts:
        - Roboto
        - Open Sans

  - type: signing